version: '3.8'
services:
  discord-bot:
    image: discord-bot:latest
    environment:
      OPENAI_API_KEY: 'YOUR_API_KEY'
      SCRAPER_API_KEY: 'YOUR_API_KEY'
      BRAVE_SEARCH_API_KEY: 'YOUR_BRAVE_SEARCH_API_KEY'
      DISCORD_TOKEN: 'YOUR_DISCORD_TOKEN'
      HUGGINGFACE_API_TOKEN: 'YOUR_HUGGINGFACE_API_TOKEN'
      HUGGINGFACEHUB_API_TOKEN: 'YOUR_HUGGINGFACEHUB_API_TOKEN'
      DEV_MODE: 'false' 
      GOOGLE_API_KEY: 'YOUR_GOOGLE_API_KEY'
    volumes:
      - /tmp/discord:/app/
